from typing import Any, List, Dict, Callable, Optional, Tuple

class keras:
    class models:
        class Sequential:
            def __init__(self, *args, **kwargs): ...
            def compile(self, *args, **kwargs): ...
            def fit(self, *args, **kwargs): ...
            def evaluate(self, *args, **kwargs): ...
            def predict(self, *args, **kwargs): ...
            def save(self, *args, **kwargs): ...
    
    class layers:
        class Dense:
            def __init__(self, *args, **kwargs): ...
        
        class Dropout:
            def __init__(self, *args, **kwargs): ...
    
    class regularizers:
        class l2:
            def __init__(self, *args, **kwargs): ...
    
    class callbacks:
        class EarlyStopping:
            def __init__(self, *args, **kwargs): ...
    
    class metrics:
        class Precision:
            def __init__(self, *args, **kwargs): ...
        
        class Recall:
            def __init__(self, *args, **kwargs): ...
    
    class optimizers:
        class Adam:
            def __init__(self, *args, **kwargs): ...

def __getattr__(name: str) -> Any: ... 